
var talleres_fisicos = [
        {
            "id": 0,
            "posicion": "1",
            "nombre": "Papelera H&H",
            "descripcion": "Papelera",
            "rubro": "Papeleria",
            "contacto": "info@papeleriah&h.com",
            "redes_sociales": "@papeleriaH&H",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Centro",
            "restricciones": "",
            "tiene_comercio": true,
            "direccion": "Güemes 176, San Miguel, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 12:00 a 22:00",
            "localidad": "Malvinas Argentinas",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/Papelería bonita 🤩.jpg",
            "coordenadas": [-34.529013308639, -58.70945616768699]
        },

        {
            "id": 0,
            "posicion": "1",
            "nombre": "Almacen Libre G",
            "descripcion": "Almacen libre de gluten",
            "rubro": "Comida",
            "contacto": "info@almacenlibreg.com",
            "redes_sociales": "@almacenlibreg",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Centro",
            "restricciones": "Libre de Gluten",
            "tiene_comercio": true,
            "direccion": "José León Suárez 2903, Los Polvorines, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 12:00 a 22:00",
            "localidad": "Malvinas Argentinas",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/comercio.jpg",
            "coordenadas": [-34.514022564805416, -58.70709434799156]
        },

        {
            "id": 0,
            "posicion": "1",
            "nombre": "Empanadas Criollas",
            "descripcion": "Las mejores empanadas Criollas",
            "rubro": "Comida",
            "contacto": "info@empanadascriollas.com",
            "redes_sociales": "@empanadascriollas",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Ciudad",
            "restricciones": "empanadas!",
            "tiene_comercio": true,
            "direccion": "Cnel. L. M. Argüero 1, San Miguel, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 12:00 a 22:00",
            "localidad": "Malvinas Argentinas",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/empanadas.jpg",
            "coordenadas": [-34.528792357133995, -58.70692773264532]
        },

        {
            "id": 0,
            "posicion": "1",
            "nombre": "Nail Art",
            "descripcion": "Emprendimiento de Uñas",
            "rubro": "Artesanias",
            "contacto": "info@nailsart.com",
            "redes_sociales": "@nailsart",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Ciudad",
            "restricciones": "No traer niños",
            "tiene_comercio": true,
            "direccion": "Carlos Gardel 1822-1900, San Miguel, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 12:00 a 22:00",
            "localidad": "Malvinas Argentinas",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/uñas.jpg",
            "coordenadas": [-34.538991244190335, -58.728178461480645]
        },

        {
            "id": 0,
            "posicion": "1",
            "nombre": "Iconic",
            "descripcion": "Tienda de ropa",
            "rubro": "Ropa",
            "contacto": "info@iconic.com",
            "redes_sociales": "@iconic",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Ciudad",
            "restricciones": "",
            "tiene_comercio": true,
            "direccion": "Urquiza 2722, San Miguel, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 12:00 a 22:00",
            "localidad": "Malvinas Argentinas",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/ropa.jpg",
            "coordenadas": [-34.529013308639, -58.71999996768699]
        },

        {
            "id": 2,
            "posicion": "2",
            "nombre": "Moda Urbana",
            "descripcion": "Tienda de ropa urbana para jóvenes con las últimas tendencias.",
            "rubro": "Ropa",
            "contacto": "contacto@modaurbana.com",
            "redes_sociales": "@modaurbana",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Sur",
            "restricciones": "No disponible para ventas al por mayor",
            "tiene_comercio": true,
            "direccion": "Pedro Medrano 1400",
            "horario": "Lunes a Viernes de 10:00 a 20:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/tiendaropa.jpg",
            "coordenadas": [-34.52138840321933, -58.713033188918184]
        },
        {
            "id": 3,
            "posicion": "3",
            "nombre": "Muebles Únicos",
            "descripcion": "Fábrica de muebles personalizados y hechos a medida.",
            "rubro": "Muebles",
            "contacto": "ventas@mueblesunicos.com",
            "redes_sociales": "@mueblesunicos",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito",
            "zona_influencia": "Norte",
            "restricciones": "Entrega solo en ciudad",
            "tiene_comercio": true,
            "direccion": "José León Suárez 2828, Los Polvorines, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 9:00 a 18:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/muebles.jpg",
            "coordenadas": [-34.51338190216312, -58.70642501518344]
        },
        {
            "id": 4,
            "posicion": "4",
            "nombre": "Arte en Cerámica",
            "descripcion": "Taller de cerámica artística y utilitaria.",
            "rubro": "Cerámica",
            "contacto": "arteenceramica@example.com",
            "redes_sociales": "@arteenceramica",
            "formas_de_pago": "Efectivo, Transferencia Bancaria",
            "zona_influencia": "Este",
            "restricciones": "Productos frágiles",
            "tiene_comercio": true,
            "direccion": "Ventura Coll 796, Malvinas Argentinas",
            "horario": "Lunes a Viernes de 14:00 a 20:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/ceramica.jpg",
            "coordenadas": [-34.513382222212, -58.71642501518344]
        },
        {
            "id": 5,
            "posicion": "5",
            "nombre": "Manos Creativas",
            "descripcion": "Artesanías únicas hechas a mano con materiales reciclados.",
            "rubro": "Artesanía",
            "contacto": "info@manoscreativas.com",
            "redes_sociales": "@manoscreativas",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, PayPal",
            "zona_influencia": "Oeste",
            "restricciones": "No envíos internacionales",
            "tiene_comercio": true,
            "direccion": "Velazquéz 2110, Los Polvorines, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 9:00 a 19:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/artesania.jpg",
            "coordenadas": [-34.52338190216312, -58.70642501518344]
        },
        {
            "id": 6,
            "posicion": "6",
            "nombre": "Belleza Natural",
            "descripcion": "Salón de belleza especializado en tratamientos naturales y orgánicos.",
            "rubro": "Belleza",
            "contacto": "belleza@natural.com",
            "redes_sociales": "@bellezanatural",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Centro",
            "restricciones": "Solo con cita previa",
            "tiene_comercio": true,
            "direccion": "RN9, Don Torcuato, Provincia de Buenos Aires",
            "horario": "Lunes a Viernes de 10:00 a 18:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/salon_belleza.jpg",
            "coordenadas": [-34.4850299379632, -58.61680482181374]   
        },
        {
            "id": 7,
            "posicion": "7",
            "nombre": "Papelería Creativa",
            "descripcion": "Tienda de artículos de papelería y manualidades.",
            "rubro": "Papelería",
            "contacto": "contacto@papeleriacreativa.com",
            "redes_sociales": "@papeleriacreativa",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Tarjeta de Débito",
            "zona_influencia": "Norte",
            "restricciones": "No disponible para ventas al por mayor",
            "tiene_comercio": true,
            "direccion": "Don Torcuato, Provincia de Buenos Aires",
            "horario": "Lunes a Sábado de 9:00 a 19:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/papeleria2.jpg",
            "coordenadas": [-34.52838190216312, -58.60642501518344]
        },
        {
            "id": 8,
            "posicion": "8",
            "nombre": "Higiene Plus",
            "descripcion": "Productos de higiene personal y limpieza para el hogar.",
            "rubro": "Higiene",
            "contacto": "info@higieneplus.com",
            "redes_sociales": "@higieneplus",
            "formas_de_pago": "Efectivo, Tarjeta de Crédito, Transferencia Bancaria",
            "zona_influencia": "Sur",
            "restricciones": "Productos químicos, mantener fuera del alcance de los niños",
            "tiene_comercio": true,
            "direccion": "Dante Alighieri 2300-2398, Los Polvorines, Provincia de Buenos Aires",
            "horario": "Lunes a Viernes de 8:00 a 17:00",
            "localidad": "Ciudad",
            "direccion_disponible": true,
            "imagen_url": "Imagenes/higene.jpg",
            "coordenadas": [-34.52338190216312, -58.70942501518344]
        }
    
]

// para usarlas en la normalización.
var direcciones_aptas = [
    {
        "nombre": "Mariano Sánchez de Loria",
        "altura": [300], 
        "partido": "Lomas de Zamora"
    },
    {
        "nombre": "Salta",
        "altura": 400, 
        "partido": "Gerli"
    },
    {
        "nombre": "Conesa",
        "altura": 800,
        "partido": "San Miguel"
    },
    {
        "nombre": "Belgrano Av.",
        "altura": 800,
        "partido": "CABA"
    }
]